name: miniosc
on:
  push:
    branches:
      - '**' # All branches for now
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_CI: yes
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Building
      run: make
    - name: Testing
      run: ./miniosctest
    - name: Create Awesome Badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 3b294d2f1aab6753ec8fd82591ccceb5
        filename: test.json
        label: Hello
        message: World
        color: orange

  build-windows:
    runs-on: windows-latest
    env:
      GITHUB_CI: yes
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive      
    - name: Building
      run: make
    - name: Testing
      run: ./miniosctest.exe



#    - name: Install dependencies (apt)
#      run: sudo apt-get install -y --no-install-recommends
#            build-essential

