name: miniosc
on:
  push:
    branches:
      - '**' # All branches for now
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_CI: yes
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Building
      run: make
    - name: Testing
      run: ./miniosctest
    - name: Time badge
      uses: RubbaBoy/BYOB@v1.3.0
      with:
        NAME: time
        LABEL: 'Updated at'
        STATUS: ${{ steps.date.outputs.data }}
        COLOR: blue
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    env:
      GITHUB_CI: yes
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive      
    - name: Building
      run: make
    - name: Testing
      run: ./miniosctest.exe



#    - name: Install dependencies (apt)
#      run: sudo apt-get install -y --no-install-recommends
#            build-essential

