name: miniosc
on:
  push:
    branches:
      - '**' # All branches for now
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_CI: yes
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Building
      run: make
    - name: Testing
      run: ./miniosctest
           echo test > test.txt

    - name: Uploading
      uses: actions/upload-artifact@v3
      with:
        path: test.txt

  build-windows:
    runs-on: windows-latest
    env:
      GITHUB_CI: yes
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive      
    - name: Building
      run: make
    - name: Testing
      run: ./miniosctest.exe



#    - name: Install dependencies (apt)
#      run: sudo apt-get install -y --no-install-recommends
#            build-essential

